export interface CvTemplate {
  id: string;
  title: string;
  description: string;
  industry: string;
  experience: string;
  image: string;
}

export const CV_TEMPLATES: CvTemplate[] = [
  {
    id: 'CV001',
    title: 'Teacher CV Example',
    description: 'Professional CV template for teachers and educators in Kenya',
    industry: 'Education',
    experience: 'All Levels',
    image: '/cv-previews/Blue Gradient Modern Geometric Elementary Teacher Resume.webp',
  },
  {
    id: 'CV002',
    title: 'Pre-School Teacher Resume',
    description: 'Specialized CV for early childhood education professionals',
    industry: 'Education',
    experience: 'Entry to Mid-Level',
    image: '/cv-previews/Blue and White Gradient Modern Pre-School Teacher Resume.webp',
  },
  {
    id: 'CV003',
    title: 'IT Project Manager Resume',
    description: 'Corporate CV template for IT professionals and project managers',
    industry: 'Technology',
    experience: 'Mid to Senior Level',
    image: '/cv-previews/Beige Minimalist Corporate IT Project Manager Resume_page-0001.webp',
  },
  {
    id: 'CV004',
    title: 'Graphic Designer Resume',
    description: 'Creative CV template for graphic designers and visual artists',
    industry: 'Design & Creative',
    experience: 'All Levels',
    image: '/cv-previews/Black Red Modern Professional Graphic Designer Resume.webp',
  },
  {
    id: 'CV005',
    title: 'Marketing Manager CV',
    description: 'Professional CV for marketing and sales professionals',
    industry: 'Sales & Marketing',
    experience: 'Mid to Senior Level',
    image: '/cv-previews/Blue Simple Professional Marketing Manager CV Resume.webp',
  },
  {
    id: 'CV006',
    title: 'Account Manager Resume',
    description: 'Professional CV template for account managers and client relations',
    industry: 'Corporate',
    experience: 'Mid-Level',
    image: '/cv-previews/Black and White Clean Professional A4 Resume for Account Manager.webp',
  },
  {
    id: 'CV007',
    title: 'Sales Manager Resume',
    description: 'Executive CV template for sales managers and business leaders',
    industry: 'Sales & Marketing',
    experience: 'Senior Level',
    image: '/cv-previews/Ivory Minimalist Sales Manager Resume_page-0001.webp',
  },
  {
    id: 'CV008',
    title: 'Fresh Graduate CV',
    description: 'Perfect CV template for recent graduates entering the job market',
    industry: 'All Industries',
    experience: 'Entry Level',
    image: '/cv-previews/Black and White Clean Professional A4 Resume (1).webp',
  },
  {
    id: 'CV009',
    title: 'Professional Minimalist CV',
    description: 'Clean and simple CV template for all professions',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Black and White Minimalistic Simple Resume.webp',
  },
  {
    id: 'CV010',
    title: 'Corporate Professional Resume',
    description: 'Standard professional CV for corporate positions',
    industry: 'Corporate',
    experience: 'All Levels',
    image: '/cv-previews/Black and White Standard Professional Resume.webp',
  },
  {
    id: 'CV011',
    title: 'Modern Professional CV',
    description: 'Contemporary CV design for modern professionals',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Black Modern Professional Resume_page-0001.webp',
  },
  {
    id: 'CV012',
    title: 'Executive CV Template',
    description: 'Premium CV template for senior executives and managers',
    industry: 'Corporate',
    experience: 'Senior Level',
    image: '/cv-previews/Black White Minimalist CV Resume.webp',
  },
  {
    id: 'CV013',
    title: 'Creative Designer Resume',
    description: 'Bold CV template for creative professionals and designers',
    industry: 'Design & Creative',
    experience: 'All Levels',
    image: '/cv-previews/Black Yellow Modern Professional Graphic Designer Resume.webp',
  },
  {
    id: 'CV014',
    title: 'Corporate Resume Template',
    description: 'Professional CV for corporate and business professionals',
    industry: 'Corporate',
    experience: 'Mid to Senior Level',
    image: '/cv-previews/Blue and Gray Simple Professional CV Resume_page-0001.webp',
  },
  {
    id: 'CV015',
    title: 'Professional CV Blue',
    description: 'Modern professional CV with blue accent design',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Blue and White Professional Corporate Resume_page-0001.webp',
  },
  {
    id: 'CV016',
    title: 'Simple Professional CV',
    description: 'Clean and simple CV template for job seekers',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Blue Simple Professional CV Resume.webp',
  },
  {
    id: 'CV017',
    title: 'Modern Blue CV Resume',
    description: 'Contemporary CV design with blue theme',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Blue White Modern CV Resume_page-0001.webp',
  },
  {
    id: 'CV018',
    title: 'Blue Professional Resume',
    description: 'Professional CV template with blue color scheme',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/blue-resume.webp',
  },
  {
    id: 'CV019',
    title: 'Academic CV Template',
    description: 'Professional CV for academic and research positions',
    industry: 'Education & Research',
    experience: 'All Levels',
    image: '/cv-previews/Curriculum CV Resume Academico Minimalista Profesional Simple Blanco.webp',
  },
  {
    id: 'CV020',
    title: 'Education Professional CV',
    description: 'Clean CV template for education professionals',
    industry: 'Education',
    experience: 'All Levels',
    image: '/cv-previews/Dark Blue and White Minimalist Education Resume_page-0001.webp',
  },
  {
    id: 'CV021',
    title: 'Creative Profile Resume',
    description: 'Professional creative CV with unique design elements',
    industry: 'Design & Creative',
    experience: 'All Levels',
    image: '/cv-previews/Dark Blue Professional Profile Creative Resume.webp',
  },
  {
    id: 'CV022',
    title: 'Finance Professional CV',
    description: 'Professional CV template for finance and accounting roles',
    industry: 'Finance & Accounting',
    experience: 'All Levels',
    image: '/cv-previews/Green and Yellow Professional CV Resume.webp',
  },
  {
    id: 'CV023',
    title: 'Modern Professional CV Green',
    description: 'Modern CV design with green accent for professionals',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Green professional modern CV resume.webp',
  },
  {
    id: 'CV024',
    title: 'Designer Creative Resume',
    description: 'Professional CV for designers with creative layout',
    industry: 'Design & Creative',
    experience: 'All Levels',
    image: '/cv-previews/Light Blue Professional Designer Creative Resume.webp',
  },
  {
    id: 'CV025',
    title: 'Modern Teal Resume',
    description: 'Contemporary CV with modern teal and charcoal design',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Teal & Charcoal Modern Resume.webp',
  },
  {
    id: 'CV026',
    title: 'Graphic Designer Professional CV',
    description: 'Minimalist CV template for graphic designers',
    industry: 'Design & Creative',
    experience: 'All Levels',
    image: '/cv-previews/White and Beige Minimalist Graphic Designer Professional Cv Resume.webp',
  },
  {
    id: 'CV027',
    title: 'Clean Professional Resume',
    description: 'Clean and professional CV template for all industries',
    industry: 'All Industries',
    experience: 'All Levels',
    image: '/cv-previews/Black and White Clean Professional A4 Resume (2).webp',
  },
  {
    id: 'CV028',
    title: 'Standard Professional CV',
    description: 'Traditional professional CV for corporate positions',
    industry: 'Corporate',
    experience: 'All Levels',
    image: '/cv-previews/Black and White Clean Professional A4 Resume.webp',
  },
];

/** The one plain/no-theme example shown for the Simple CV tier. */
export const SIMPLE_CV_EXAMPLE: CvTemplate = CV_TEMPLATES.find((t) => t.id === 'CV028')!;

export const WHATSAPP_NUMBER = '254702767266';
